# 第6章: 単語ベクトル

単語の意味を実ベクトルで表現する単語ベクトル（単語埋め込み）に関して、以下の処理を行うプログラムを作成せよ。

In [8]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.6 MB/s eta 0:00:00
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.9 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim) (7.3.0.post1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)
Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 47.7 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 54.1 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 16.9 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

## 50. 単語ベクトルの読み込みと表示

Google Newsデータセット（約1,000億単語）での[学習済み単語ベクトル](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing)（300万単語・フレーズ、300次元）をダウンロードし、"United States"の単語ベクトルを表示せよ。ただし、"United States"は内部的には"United_States"と表現されていることに注意せよ。

In [2]:
from gensim.models import KeyedVectors

In [3]:
model = KeyedVectors.load_word2vec_format('/content/drive/MyDrive/nlp100/lesson06/GoogleNews-vectors-negative300.bin', binary = True)
us_vec = model['United_States']
us_vec

array([-3.61328125e-02, -4.83398438e-02,  2.35351562e-01,  1.74804688e-01,
       -1.46484375e-01, -7.42187500e-02, -1.01562500e-01, -7.71484375e-02,
        1.09375000e-01, -5.71289062e-02, -1.48437500e-01, -6.00585938e-02,
        1.74804688e-01, -7.71484375e-02,  2.58789062e-02, -7.66601562e-02,
       -3.80859375e-02,  1.35742188e-01,  3.75976562e-02, -4.19921875e-02,
       -3.56445312e-02,  5.34667969e-02,  3.68118286e-04, -1.66992188e-01,
       -1.17187500e-01,  1.41601562e-01, -1.69921875e-01, -6.49414062e-02,
       -1.66992188e-01,  1.00585938e-01,  1.15722656e-01, -2.18750000e-01,
       -9.86328125e-02, -2.56347656e-02,  1.23046875e-01, -3.54003906e-02,
       -1.58203125e-01, -1.60156250e-01,  2.94189453e-02,  8.15429688e-02,
        6.88476562e-02,  1.87500000e-01,  6.49414062e-02,  1.15234375e-01,
       -2.27050781e-02,  3.32031250e-01, -3.27148438e-02,  1.77734375e-01,
       -2.08007812e-01,  4.54101562e-02, -1.23901367e-02,  1.19628906e-01,
        7.44628906e-03, -9.03320312e-03,  1.14257812e-01,  1.69921875e-01,
       -2.38281250e-01, -2.79541016e-02, -1.21093750e-01,  2.47802734e-02,
        7.71484375e-02, -2.81982422e-02, -4.71191406e-02,  1.78222656e-02,
       -1.23046875e-01, -5.32226562e-02,  2.68554688e-02, -3.11279297e-02,
       -5.59082031e-02, -5.00488281e-02, -3.73535156e-02,  1.25976562e-01,
        5.61523438e-02,  1.51367188e-01,  4.29687500e-02, -2.08007812e-01,
       -4.78515625e-02,  2.78320312e-02,  1.81640625e-01,  2.20703125e-01,
       -3.61328125e-02, -8.39843750e-02, -3.69548798e-05, -9.52148438e-02,
       -1.25000000e-01, -1.95312500e-01, -1.50390625e-01, -4.15039062e-02,
        1.31835938e-01,  1.17675781e-01,  1.91650391e-02,  5.51757812e-02,
       -9.42382812e-02, -1.08886719e-01,  7.32421875e-02, -1.15234375e-01,
        8.93554688e-02, -1.40625000e-01,  1.45507812e-01,  4.49218750e-02,
       -1.10473633e-02, -1.62353516e-02,  4.05883789e-03,  3.75976562e-02,
       -6.98242188e-02, -5.46875000e-02,  2.17285156e-02, -9.47265625e-02,
        4.24804688e-02,  1.81884766e-02, -1.73339844e-02,  4.63867188e-02,
       -1.42578125e-01,  1.99218750e-01,  1.10839844e-01,  2.58789062e-02,
       -7.08007812e-02, -5.54199219e-02,  3.45703125e-01,  1.61132812e-01,
       -2.44140625e-01, -2.59765625e-01, -9.71679688e-02,  8.00781250e-02,
       -8.78906250e-02, -7.22656250e-02,  1.42578125e-01, -8.54492188e-02,
       -3.18359375e-01,  8.30078125e-02,  6.34765625e-02,  1.64062500e-01,
       -1.92382812e-01, -1.17675781e-01, -5.41992188e-02, -1.56250000e-01,
       -1.21582031e-01, -4.95605469e-02,  1.20117188e-01, -3.83300781e-02,
        5.51757812e-02, -8.97216797e-03,  4.32128906e-02,  6.93359375e-02,
        8.93554688e-02,  2.53906250e-01,  1.65039062e-01,  1.64062500e-01,
       -1.41601562e-01,  4.58984375e-02,  1.97265625e-01, -8.98437500e-02,
        3.90625000e-02, -1.51367188e-01, -8.60595703e-03, -1.17675781e-01,
       -1.97265625e-01, -1.12792969e-01,  1.29882812e-01,  1.96289062e-01,
        1.56402588e-03,  3.93066406e-02,  2.17773438e-01, -1.43554688e-01,
        6.03027344e-02, -1.35742188e-01,  1.16210938e-01, -1.59912109e-02,
        2.79296875e-01,  1.46484375e-01, -1.19628906e-01,  1.76757812e-01,
        1.28906250e-01, -1.49414062e-01,  6.93359375e-02, -1.72851562e-01,
        9.22851562e-02,  1.33056641e-02, -2.00195312e-01, -9.76562500e-02,
       -1.65039062e-01, -2.46093750e-01, -2.35595703e-02, -2.11914062e-01,
        1.84570312e-01, -1.85546875e-02,  2.16796875e-01,  5.05371094e-02,
        2.02636719e-02,  4.25781250e-01,  1.28906250e-01, -2.77099609e-02,
        1.29882812e-01, -1.15722656e-01, -2.05078125e-02,  1.49414062e-01,
        7.81250000e-03, -2.05078125e-01, -8.05664062e-02, -2.67578125e-01,
       -2.29492188e-02, -8.20312500e-02,  8.64257812e-02,  7.61718750e-02,
       -3.66210938e-02,  5.22460938e-02, -1.22070312e-01, -1.44042969e-02,
       -2.69531250e-01,  8.44726562e-02, -2.52685547e-02, -2.96630859e-02,
       -1.68945312e-01,  1.93359375e-01, -1.08398438e-01,  1.94091797e-02,
       -1.80664062e-01,  1.93359375e-01, -7.08007812e-02,  5.85937500e-02,
       -1.01562500e-01, -1.31835938e-01,  7.51953125e-02, -7.66601562e-02,
        3.37219238e-03, -8.59375000e-02,  1.25000000e-01,  2.92968750e-02,
        1.70898438e-01, -9.37500000e-02, -1.09375000e-01, -2.50244141e-02,
        2.11914062e-01, -4.44335938e-02,  6.12792969e-02,  2.62451172e-02,
       -1.77734375e-01,  1.23046875e-01, -7.42187500e-02, -1.67968750e-01,
       -1.08886719e-01, -9.04083252e-04, -7.37304688e-02,  5.49316406e-02,
        6.03027344e-02,  8.39843750e-02,  9.17968750e-02, -1.32812500e-01,
        1.22070312e-01, -8.78906250e-03,  1.19140625e-01, -1.94335938e-01,
       -6.64062500e-02, -2.07031250e-01,  7.37304688e-02,  8.93554688e-02,
        1.81884766e-02, -1.20605469e-01, -2.61230469e-02,  2.67333984e-02,
        7.76367188e-02, -8.30078125e-02,  6.78710938e-02, -3.54003906e-02,
        3.10546875e-01, -2.42919922e-02, -1.41601562e-01, -2.08007812e-01,
       -4.57763672e-03, -6.54296875e-02, -4.95605469e-02,  2.22656250e-01,
        1.53320312e-01, -1.38671875e-01, -5.24902344e-02,  4.24804688e-02,
       -2.38281250e-01,  1.56250000e-01,  5.83648682e-04, -1.20605469e-01,
       -9.22851562e-02, -4.44335938e-02,  3.61328125e-02, -1.86767578e-02,
       -8.25195312e-02, -8.25195312e-02, -4.05273438e-02,  1.19018555e-02,
        1.69921875e-01, -2.80761719e-02,  3.03649902e-03,  9.32617188e-02,
       -8.49609375e-02,  1.57470703e-02,  7.03125000e-02,  1.62353516e-02,
       -2.27050781e-02,  3.51562500e-02,  2.47070312e-01, -2.67333984e-02],
      dtype=float32)

## 51. 単語の類似度

"United States"と"U.S."のコサイン類似度を計算せよ。

In [5]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [7]:
vec_1 = model['United_States']
vec_2 = model['U.S.']
cos_sim = cosine_similarity([vec_1], [vec_2])
print(cos_sim)

[[0.7310775]]

## 52. 類似度の高い単語10件

"United States"とコサイン類似度が高い10語と、その類似度を出力せよ。

In [6]:
model.most_similar('United_States', topn = 10)

[('Unites_States', 0.7877248525619507),
 ('Untied_States', 0.7541370987892151),
 ('United_Sates', 0.7400724291801453),
 ('U.S.', 0.7310774326324463),
 ('theUnited_States', 0.6404393911361694),
 ('America', 0.6178410053253174),
 ('UnitedStates', 0.6167312264442444),
 ('Europe', 0.6132988929748535),
 ('countries', 0.6044804453849792),
 ('Canada', 0.601906955242157)]

## 53. 加法構成性によるアナロジー

"Spain"の単語ベクトルから"Madrid"のベクトルを引き、"Athens"のベクトルを足したベクトルを計算し、そのベクトルと類似度の高い10語とその類似度を出力せよ。

In [7]:
model.most_similar(model['Spain'] - model['Madrid'] + model['Athens'], topn = 10)

[('Athens', 0.7528455853462219),
 ('Greece', 0.6685472130775452),
 ('Aristeidis_Grigoriadis', 0.5495778322219849),
 ('Ioannis_Drymonakos', 0.5361457467079163),
 ('Greeks', 0.5351786017417908),
 ('Ioannis_Christou', 0.5330225825309753),
 ('Hrysopiyi_Devetzi', 0.5088489055633545),
 ('Iraklion', 0.5059264302253723),
 ('Greek', 0.5040615797042847),
 ('Athens_Greece', 0.5034108757972717)]

In [8]:
model.most_similar(positive = ['Spain', 'Athens'], negative = ['Madrid'], topn = 10)

[('Greece', 0.6898480653762817),
 ('Aristeidis_Grigoriadis', 0.560684859752655),
 ('Ioannis_Drymonakos', 0.5552908778190613),
 ('Greeks', 0.545068621635437),
 ('Ioannis_Christou', 0.5400862097740173),
 ('Hrysopiyi_Devetzi', 0.5248445272445679),
 ('Heraklio', 0.5207759737968445),
 ('Athens_Greece', 0.516880989074707),
 ('Lithuania', 0.5166865587234497),
 ('Iraklion', 0.5146791338920593)]

## 54. アナロジーデータでの実験

[単語アナロジーの評価データ](http://download.tensorflow.org/data/questions-words.txt)をダウンロードし、国と首都に関する事例（`: capital-common-countries`セクション）に対して、vec(2列目の単語) - vec(1列目の単語) + vec(3列目の単語)を計算し、そのベクトルと類似度が最も高い単語と、その類似度を求めよ。求めた単語と類似度は、各事例と一緒に記録せよ。

In [9]:
import pandas as pd
import re

In [10]:
data = {'Word1': [], 'Word2': [], 'Word3': [], 'Word4(Correct)': [], 'Category': []}
with open('/content/drive/MyDrive/nlp100/lesson06/questions-words.txt', 'r') as file:
  category = ''
  for line in file:
    line = line.rstrip('\n')
    if ':' in line:
      category = re.sub('\s*:\s*(.+)', r'\1', line)
      continue
    else:
      words = re.split('\s+', line)
      data['Word1'].append(words[0])
      data['Word2'].append(words[1])
      data['Word3'].append(words[2])
      data['Word4(Correct)'].append(words[3])
      data['Category'].append(category)
df = pd.DataFrame(data)

In [11]:
df_capital_common_countries = df[df['Category'] == 'capital-common-countries']

similary_word = []
similary_value = []
for index, row in df_capital_common_countries.iterrows():
  if index % 999 == 0:
    print(f'== {index}行目 ==')
  most_similar_info = model.most_similar(model[row[1]] - model[row[0]] + model[row[2]], topn = 1)[0]
  # most_similar_info = model.most_similar(positive = [row[0], row[2]], negative = [row[1]], topn = 1)[0] # 推奨
  similary_word.append(most_similar_info[0])
  similary_value.append(most_similar_info[1])

similary_word = pd.Series(similary_word)
similary_value = pd.Series(similary_value)
df_capital_common_countries['Similar_Word'] = similary_word
df_capital_common_countries['Similar_Value'] = similary_value
df_capital_common_countries

== 0行目 ==

/tmp/ipython-input-1297483717.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  most_similar_info = model.most_similar(model[row[1]] - model[row[0]] + model[row[2]], topn = 1)[0]
/tmp/ipython-input-1297483717.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_evaluated['Similar_Word'] = similary_word
/tmp/ipython-input-1297483717.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_evaluated['Similar_Value'] = similary_value

,Word1,Word2,Word3,Word4(Correct),Category,Similar_Word,Similar_Value
0,Athens,Greece,Baghdad,Iraq,capital-common-countries,Baghdad,0.748983
1,Athens,Greece,Bangkok,Thailand,capital-common-countries,Bangkok,0.743114
2,Athens,Greece,Beijing,China,capital-common-countries,China,0.718659
3,Athens,Greece,Berlin,Germany,capital-common-countries,Germany,0.672089
4,Athens,Greece,Bern,Switzerland,capital-common-countries,Bern,0.690234
...,...,...,...,...,...,...,...
501,Tokyo,Japan,Ottawa,Canada,capital-common-countries,Ottawa,0.736568
502,Tokyo,Japan,Paris,France,capital-common-countries,France,0.749786
503,Tokyo,Japan,Rome,Italy,capital-common-countries,Rome,0.704386
504,Tokyo,Japan,Stockholm,Sweden,capital-common-countries,Sweden,0.798991
505,Tokyo,Japan,Tehran,Iran,capital-common-countries,Iran,0.846599

In [12]:
df_capital_common_countries.to_csv('/content/drive/MyDrive/nlp100/lesson06/df_evaluated.csv', index = False)

## 55. アナロジータスクでの正解率

54の実行結果を用い、意味的アナロジー（semantic analogy）と文法的アナロジー（syntactic analogy）の正解率を測定せよ。

In [43]:
df_semantic = df[~df['Category'].str.contains('gram')] # 意味的アナロジー

similary_word = []
similary_value = []
for index, row in df_semantic.iterrows():
  if index % 999 == 0:
    print(f'== {index}行目 ==')
  # most_similar_info = model.most_similar(model[row[1]] - model[row[0]] + model[row[2]], topn = 1)[0]
  most_similar_info = model.most_similar(positive = [row[1], row[2]], negative = [row[0]], topn = 1)[0] # 推奨
  similary_word.append(most_similar_info[0])
  similary_value.append(most_similar_info[1])

similary_word = pd.Series(similary_word)
similary_value = pd.Series(similary_value)
df_semantic['Similar_Word'] = similary_word
df_semantic['Similar_Value'] = similary_value
df_semantic

== 0行目 ==

/tmp/ipython-input-2912385613.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  most_similar_info = model.most_similar(positive = [row[1], row[2]], negative = [row[0]], topn = 1)[0] # 推奨

== 999行目 ==
== 1998行目 ==
== 2997行目 ==
== 3996行目 ==
== 4995行目 ==
== 5994行目 ==
== 6993行目 ==
== 7992行目 ==

/tmp/ipython-input-2912385613.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_semantic['Similar_Word'] = similary_word
/tmp/ipython-input-2912385613.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_semantic['Similar_Value'] = similary_value

,Word1,Word2,Word3,Word4(Correct),Category,Similar_Word,Similar_Value
0,Athens,Greece,Baghdad,Iraq,capital-common-countries,Iraqi,0.635187
1,Athens,Greece,Bangkok,Thailand,capital-common-countries,Thailand,0.713767
2,Athens,Greece,Beijing,China,capital-common-countries,China,0.723578
3,Athens,Greece,Berlin,Germany,capital-common-countries,Germany,0.673462
4,Athens,Greece,Bern,Switzerland,capital-common-countries,Switzerland,0.491975
...,...,...,...,...,...,...,...
8864,uncle,aunt,son,daughter,family,daughter,0.887963
8865,uncle,aunt,sons,daughters,family,daughters,0.877204
8866,uncle,aunt,stepbrother,stepsister,family,mother,0.618603
8867,uncle,aunt,stepfather,stepmother,family,mother,0.778509
8868,uncle,aunt,stepson,stepdaughter,family,stepdaughter,0.753163

In [44]:
df_syntactic = df[df['Category'].str.contains('gram')] # 文法的アナロジー

similary_word = []
similary_value = []
for index, row in df_syntactic.iterrows():
  if index % 999 == 0:
    print(f'== {index}行目 ==')
  # most_similar_info = model.most_similar(model[row[1]] - model[row[0]] + model[row[2]], topn = 1)[0]
  most_similar_info = model.most_similar(positive = [row[1], row[2]], negative = [row[0]], topn = 1)[0] # 推奨
  similary_word.append(most_similar_info[0])
  similary_value.append(most_similar_info[1])

similary_word = pd.Series(similary_word)
similary_value = pd.Series(similary_value)
df_syntactic['Similar_Word'] = similary_word
df_syntactic['Similar_Value'] = similary_value
df_syntactic

/tmp/ipython-input-145043718.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  most_similar_info = model.most_similar(positive = [row[1], row[2]], negative = [row[0]], topn = 1)[0] # 推奨

== 8991行目 ==
== 9990行目 ==
== 10989行目 ==
== 11988行目 ==
== 12987行目 ==
== 13986行目 ==
== 14985行目 ==
== 15984行目 ==
== 16983行目 ==
== 17982行目 ==
== 18981行目 ==

/tmp/ipython-input-145043718.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_syntactic['Similar_Word'] = similary_word
/tmp/ipython-input-145043718.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_syntactic['Similar_Value'] = similary_value

,Word1,Word2,Word3,Word4(Correct),Category,Similar_Word,Similar_Value
8869,amazing,amazingly,apparent,apparently,gram1-adjective-to-adverb,greenback,0.670671
8870,amazing,amazingly,calm,calmly,gram1-adjective-to-adverb,donkeys,0.802969
8871,amazing,amazingly,cheerful,cheerfully,gram1-adjective-to-adverb,dreams,0.767778
8872,amazing,amazingly,complete,completely,gram1-adjective-to-adverb,eagles,0.723456
8873,amazing,amazingly,efficient,efficiently,gram1-adjective-to-adverb,elephants,0.826270
...,...,...,...,...,...,...,...
19539,write,writes,talk,talks,gram9-plural-verbs,NaN,NaN
19540,write,writes,think,thinks,gram9-plural-verbs,NaN,NaN
19541,write,writes,vanish,vanishes,gram9-plural-verbs,NaN,NaN
19542,write,writes,walk,walks,gram9-plural-verbs,NaN,NaN
19543,write,writes,work,works,gram9-plural-verbs,NaN,NaN

In [49]:
df_semantic.to_csv('/content/drive/MyDrive/nlp100/lesson06/df_semantic.csv', index = False)
df_syntactic.to_csv('/content/drive/MyDrive/nlp100/lesson06/df_syntactic.csv', index = False)

In [51]:
corrects = 0
for index, row in df_semantic.iterrows():
  if row['Similar_Word'] == row['Word4(Correct)']:
    corrects += 1
print(f'意味的アナロジーの正解率: {corrects / len(df_semantic)}')

意味的アナロジーの正解率: 0.7308602999210734

In [63]:
df_syntactic = pd.read_csv('/content/drive/MyDrive/nlp100/lesson06/df_syntactic.csv')

similary_word = []
similary_value = []
for index, row in df_syntactic.iterrows():
  if index % 999 == 0:
    print(f'== {index+1}行目 ==')
  most_similar_info = model.most_similar(positive = [row[1], row[2]], negative = [row[0]], topn = 1)[0]
  similary_word.append(most_similar_info[0])
  similary_value.append(most_similar_info[1])

similary_word = pd.Series(similary_word)
similary_value = pd.Series(similary_value)
df_syntactic['Similar_Word'] = similary_word
df_syntactic['Similar_Value'] = similary_value
df_syntactic.to_csv('/content/drive/MyDrive/nlp100/lesson06/df_syntactic_check.csv', index = False)

== 1行目 ==

/tmp/ipython-input-1804026792.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  most_similar_info = model.most_similar(positive = [row[1], row[2]], negative = [row[0]], topn = 1)[0]

== 1000行目 ==
== 1999行目 ==
== 2998行目 ==
== 3997行目 ==
== 4996行目 ==
== 5995行目 ==
== 6994行目 ==
== 7993行目 ==
== 8992行目 ==
== 9991行目 ==

In [64]:
corrects = 0
for index, row in df_syntactic.iterrows():
  if row['Similar_Word'] == row['Word4(Correct)']:
    corrects += 1
print(f'文法的アナロジーの正解率: {corrects / len(df_syntactic)}')

文法的アナロジーの正解率: 0.7400468384074942

## 56. WordSimilarity-353での評価

[The WordSimilarity-353 Test Collection](http://www.gabrilovich.com/resources/data/wordsim353/wordsim353.html)の評価データをダウンロードし、単語ベクトルにより計算される類似度のランキングと、人間の類似度判定のランキングの間のスピアマン相関係数を計算せよ。

In [16]:
from scipy.stats import spearmanr

In [14]:
df = pd.read_csv('/content/drive/MyDrive/nlp100/lesson06/wordsim353/combined.csv')
similary_value = []
for index, row in df.iterrows():
  similary_value.append(model.similarity(row['Word 1'], row['Word 2']))
df['System'] = pd.Series(similary_value)
print(df[['Human (mean)', 'System']].corr(method = 'spearman')) # methodのdefaultはpearson,

              Human (mean)    System
Human (mean)      1.000000  0.700017
System            0.700017  1.000000

In [18]:
# Spearmanの順位相関係数とp値を計算
corr, p_value = spearmanr(df['Human (mean)'], df['System'])

print(f"スピアマンの順位相関係数: {corr}")
print(f"p値: {p_value}")

# 統計的有意性の判断
if p_value < 0.05:
    print("相関は統計的に有意です（p < 0.05）。")
else:
    print("相関は統計的に有意ではありません（p >= 0.05）。")

スピアマンの順位相関係数: 0.7000166486272194
p値: 2.86866666051422e-53
相関は統計的に有意です（p < 0.05）。

## 57. k-meansクラスタリング

国名に関する単語ベクトルを抽出し、k-meansクラスタリングをクラスタ数k=5として実行せよ。

## 58. Ward法によるクラスタリング

国名に関する単語ベクトルに対し、Ward法による階層型クラスタリングを実行せよ。さらに、クラスタリング結果をデンドログラムとして可視化せよ。

## 59. t-SNEによる可視化

ベクトル空間上の国名に関する単語ベクトルをt-SNEで可視化せよ。